
export type ContentPack = {
  id: string;
  label: string;
  emoji: string;
  isSpicy?: boolean;
  truths: string[];
  dares: string[];
};

export const TRUTH_DARE_PACKS: ContentPack[] = [
  {
    id: "friendly",
    label: "😊 Friendly",
    emoji: "😊",
    truths: [
  "What is your most embarrassing moment?",
  "Who is your crush?",
  "Have you ever lied to get out of trouble?",
  "What's the worst food you've ever tasted?",
  "What is a secret you kept from your parents?",
  "Who is your favorite person in the room?",
  "What's your worst habit?",
  "Have you ever peed in the pool?",
  "What is the longest you've gone without showering?",
  "What's the weirdest dream you've ever had?",
  "When was the last time you felt truly happy?",
  "When was the last time you felt truly sad?",
  "When was the last time you felt truly angry?",
  "When was the last time you felt truly confused?",
  "When was the last time you felt truly excited?",
  "When was the last time you felt truly nervous?",
  "What is the most embarrassing thing that happened to you at school?",
  "What is the most embarrassing thing that happened to you at work?",
  "What is the most embarrassing thing that happened to you at a party?",
  "What is the most embarrassing thing that happened to you at vacation?",
  "What is the most embarrassing thing that happened to you at the supermarket?",
  "What is the most embarrassing thing that happened to you at the gym?",
  "If you had $50 to spend today, what would you buy?",
  "If you had $100 to spend today, what would you buy?",
  "If you had $150 to spend today, what would you buy?",
  "If you had $200 to spend today, what would you buy?",
  "If you had $250 to spend today, what would you buy?",
  "If you had $300 to spend today, what would you buy?",
  "If you had $350 to spend today, what would you buy?",
  "If you had $400 to spend today, what would you buy?",
  "If you had $450 to spend today, what would you buy?",
  "If you had $500 to spend today, what would you buy?",
  "If you had $550 to spend today, what would you buy?",
  "If you had $600 to spend today, what would you buy?",
  "If you had $650 to spend today, what would you buy?",
  "If you had $700 to spend today, what would you buy?",
  "If you had $750 to spend today, what would you buy?",
  "If you had $800 to spend today, what would you buy?",
  "If you had $850 to spend today, what would you buy?",
  "If you had $900 to spend today, what would you buy?",
  "If you had $950 to spend today, what would you buy?",
  "If you had $1000 to spend today, what would you buy?",
  "If you had $1050 to spend today, what would you buy?",
  "If you had $1100 to spend today, what would you buy?",
  "If you had $1150 to spend today, what would you buy?",
  "If you had $1200 to spend today, what would you buy?",
  "If you had $1250 to spend today, what would you buy?",
  "If you had $1300 to spend today, what would you buy?",
  "If you had $1350 to spend today, what would you buy?",
  "If you had $1400 to spend today, what would you buy?",
  "If you had $1450 to spend today, what would you buy?",
  "If you had $1500 to spend today, what would you buy?",
  "If you had $1550 to spend today, what would you buy?",
  "If you had $1600 to spend today, what would you buy?",
  "If you had $1650 to spend today, what would you buy?",
  "If you had $1700 to spend today, what would you buy?",
  "If you had $1750 to spend today, what would you buy?",
  "If you had $1800 to spend today, what would you buy?",
  "If you had $1850 to spend today, what would you buy?",
  "If you had $1900 to spend today, what would you buy?",
  "If you had $1950 to spend today, what would you buy?",
  "If you had $2000 to spend today, what would you buy?",
  "If you had $2050 to spend today, what would you buy?",
  "If you had $2100 to spend today, what would you buy?",
  "If you had $2150 to spend today, what would you buy?",
  "If you had $2200 to spend today, what would you buy?",
  "If you had $2250 to spend today, what would you buy?",
  "If you had $2300 to spend today, what would you buy?",
  "If you had $2350 to spend today, what would you buy?",
  "If you had $2400 to spend today, what would you buy?",
  "If you had $2450 to spend today, what would you buy?",
  "If you had $2500 to spend today, what would you buy?",
  "If you had $2550 to spend today, what would you buy?",
  "If you had $2600 to spend today, what would you buy?",
  "If you had $2650 to spend today, what would you buy?",
  "If you had $2700 to spend today, what would you buy?",
  "If you had $2750 to spend today, what would you buy?",
  "If you had $2800 to spend today, what would you buy?",
  "If you had $2850 to spend today, what would you buy?",
  "If you had $2900 to spend today, what would you buy?",
  "If you had $2950 to spend today, what would you buy?",
  "If you had $3000 to spend today, what would you buy?",
  "If you had $3050 to spend today, what would you buy?",
  "If you had $3100 to spend today, what would you buy?",
  "If you had $3150 to spend today, what would you buy?",
  "If you had $3200 to spend today, what would you buy?",
  "If you had $3250 to spend today, what would you buy?",
  "If you had $3300 to spend today, what would you buy?",
  "If you had $3350 to spend today, what would you buy?",
  "If you had $3400 to spend today, what would you buy?",
  "If you had $3450 to spend today, what would you buy?",
  "If you had $3500 to spend today, what would you buy?",
  "If you had $3550 to spend today, what would you buy?",
  "If you had $3600 to spend today, what would you buy?",
  "If you had $3650 to spend today, what would you buy?",
  "If you had $3700 to spend today, what would you buy?",
  "If you had $3750 to spend today, what would you buy?",
  "If you had $3800 to spend today, what would you buy?",
  "If you had $3850 to spend today, what would you buy?",
  "If you had $3900 to spend today, what would you buy?",
  "If you had $3950 to spend today, what would you buy?",
  "If you had $4000 to spend today, what would you buy?",
  "If you had $4050 to spend today, what would you buy?",
  "If you had $4100 to spend today, what would you buy?",
  "If you had $4150 to spend today, what would you buy?",
  "If you had $4200 to spend today, what would you buy?",
  "If you had $4250 to spend today, what would you buy?",
  "If you had $4300 to spend today, what would you buy?",
  "If you had $4350 to spend today, what would you buy?",
  "If you had $4400 to spend today, what would you buy?",
  "If you had $4450 to spend today, what would you buy?",
  "If you had $4500 to spend today, what would you buy?",
  "If you had $4550 to spend today, what would you buy?",
  "If you had $4600 to spend today, what would you buy?",
  "If you had $4650 to spend today, what would you buy?",
  "If you had $4700 to spend today, what would you buy?",
  "If you had $4750 to spend today, what would you buy?",
  "If you had $4800 to spend today, what would you buy?",
  "If you had $4850 to spend today, what would you buy?",
  "If you had $4900 to spend today, what would you buy?",
  "If you had $4950 to spend today, what would you buy?",
  "If you had $5000 to spend today, what would you buy?",
  "If you had $5050 to spend today, what would you buy?",
  "If you had $5100 to spend today, what would you buy?",
  "If you had $5150 to spend today, what would you buy?",
  "If you had $5200 to spend today, what would you buy?",
  "If you had $5250 to spend today, what would you buy?",
  "If you had $5300 to spend today, what would you buy?",
  "If you had $5350 to spend today, what would you buy?",
  "If you had $5400 to spend today, what would you buy?",
  "If you had $5450 to spend today, what would you buy?",
  "If you had $5500 to spend today, what would you buy?",
  "If you had $5550 to spend today, what would you buy?",
  "If you had $5600 to spend today, what would you buy?",
  "If you had $5650 to spend today, what would you buy?",
  "If you had $5700 to spend today, what would you buy?",
  "If you had $5750 to spend today, what would you buy?",
  "If you had $5800 to spend today, what would you buy?",
  "If you had $5850 to spend today, what would you buy?",
  "If you had $5900 to spend today, what would you buy?",
  "If you had $5950 to spend today, what would you buy?",
  "If you had $6000 to spend today, what would you buy?",
  "If you had $6050 to spend today, what would you buy?",
  "If you had $6100 to spend today, what would you buy?",
  "If you had $6150 to spend today, what would you buy?",
  "If you had $6200 to spend today, what would you buy?",
  "If you had $6250 to spend today, what would you buy?",
  "If you had $6300 to spend today, what would you buy?",
  "If you had $6350 to spend today, what would you buy?",
  "If you had $6400 to spend today, what would you buy?",
  "If you had $6450 to spend today, what would you buy?",
  "If you had $6500 to spend today, what would you buy?",
  "If you had $6550 to spend today, what would you buy?",
  "If you had $6600 to spend today, what would you buy?",
  "If you had $6650 to spend today, what would you buy?",
  "If you had $6700 to spend today, what would you buy?",
  "If you had $6750 to spend today, what would you buy?",
  "If you had $6800 to spend today, what would you buy?",
  "If you had $6850 to spend today, what would you buy?",
  "If you had $6900 to spend today, what would you buy?",
  "If you had $6950 to spend today, what would you buy?",
  "If you had $7000 to spend today, what would you buy?",
  "If you had $7050 to spend today, what would you buy?",
  "If you had $7100 to spend today, what would you buy?",
  "If you had $7150 to spend today, what would you buy?",
  "If you had $7200 to spend today, what would you buy?",
  "If you had $7250 to spend today, what would you buy?",
  "If you had $7300 to spend today, what would you buy?",
  "If you had $7350 to spend today, what would you buy?",
  "If you had $7400 to spend today, what would you buy?",
  "If you had $7450 to spend today, what would you buy?",
  "If you had $7500 to spend today, what would you buy?",
  "If you had $7550 to spend today, what would you buy?",
  "If you had $7600 to spend today, what would you buy?",
  "If you had $7650 to spend today, what would you buy?",
  "If you had $7700 to spend today, what would you buy?",
  "If you had $7750 to spend today, what would you buy?",
  "If you had $7800 to spend today, what would you buy?",
  "If you had $7850 to spend today, what would you buy?",
  "If you had $7900 to spend today, what would you buy?",
  "If you had $7950 to spend today, what would you buy?",
  "If you had $8000 to spend today, what would you buy?",
  "If you had $8050 to spend today, what would you buy?",
  "If you had $8100 to spend today, what would you buy?",
  "If you had $8150 to spend today, what would you buy?",
  "If you had $8200 to spend today, what would you buy?",
  "If you had $8250 to spend today, what would you buy?",
  "If you had $8300 to spend today, what would you buy?",
  "If you had $8350 to spend today, what would you buy?",
  "If you had $8400 to spend today, what would you buy?",
  "If you had $8450 to spend today, what would you buy?",
  "If you had $8500 to spend today, what would you buy?",
  "If you had $8550 to spend today, what would you buy?",
  "If you had $8600 to spend today, what would you buy?",
  "If you had $8650 to spend today, what would you buy?",
  "If you had $8700 to spend today, what would you buy?",
  "If you had $8750 to spend today, what would you buy?",
  "If you had $8800 to spend today, what would you buy?",
  "If you had $8850 to spend today, what would you buy?",
  "If you had $8900 to spend today, what would you buy?",
  "If you had $8950 to spend today, what would you buy?",
  "If you had $9000 to spend today, what would you buy?",
  "If you had $9050 to spend today, what would you buy?",
  "If you had $9100 to spend today, what would you buy?",
  "If you had $9150 to spend today, what would you buy?",
  "If you had $9200 to spend today, what would you buy?",
  "If you had $9250 to spend today, what would you buy?",
  "If you had $9300 to spend today, what would you buy?",
  "If you had $9350 to spend today, what would you buy?",
  "If you had $9400 to spend today, what would you buy?",
  "If you had $9450 to spend today, what would you buy?",
  "If you had $9500 to spend today, what would you buy?",
  "If you had $9550 to spend today, what would you buy?",
  "If you had $9600 to spend today, what would you buy?",
  "If you had $9650 to spend today, what would you buy?",
  "If you had $9700 to spend today, what would you buy?",
  "If you had $9750 to spend today, what would you buy?",
  "If you had $9800 to spend today, what would you buy?",
  "If you had $9850 to spend today, what would you buy?",
  "If you had $9900 to spend today, what would you buy?",
  "If you had $9950 to spend today, what would you buy?",
  "If you had $10000 to spend today, what would you buy?",
  "If you had $10050 to spend today, what would you buy?",
  "If you had $10100 to spend today, what would you buy?",
  "If you had $10150 to spend today, what would you buy?",
  "If you had $10200 to spend today, what would you buy?",
  "If you had $10250 to spend today, what would you buy?",
  "If you had $10300 to spend today, what would you buy?",
  "If you had $10350 to spend today, what would you buy?",
  "If you had $10400 to spend today, what would you buy?",
  "If you had $10450 to spend today, what would you buy?",
  "If you had $10500 to spend today, what would you buy?",
  "If you had $10550 to spend today, what would you buy?",
  "If you had $10600 to spend today, what would you buy?",
  "If you had $10650 to spend today, what would you buy?",
  "If you had $10700 to spend today, what would you buy?",
  "If you had $10750 to spend today, what would you buy?",
  "If you had $10800 to spend today, what would you buy?",
  "If you had $10850 to spend today, what would you buy?",
  "If you had $10900 to spend today, what would you buy?",
  "If you had $10950 to spend today, what would you buy?",
  "If you had $11000 to spend today, what would you buy?",
  "If you had $11050 to spend today, what would you buy?",
  "If you had $11100 to spend today, what would you buy?",
  "If you had $11150 to spend today, what would you buy?",
  "If you had $11200 to spend today, what would you buy?",
  "If you had $11250 to spend today, what would you buy?",
  "If you had $11300 to spend today, what would you buy?",
  "If you had $11350 to spend today, what would you buy?",
  "If you had $11400 to spend today, what would you buy?",
  "If you had $11450 to spend today, what would you buy?",
  "If you had $11500 to spend today, what would you buy?",
  "If you had $11550 to spend today, what would you buy?",
  "If you had $11600 to spend today, what would you buy?",
  "If you had $11650 to spend today, what would you buy?",
  "If you had $11700 to spend today, what would you buy?",
  "If you had $11750 to spend today, what would you buy?",
  "If you had $11800 to spend today, what would you buy?",
  "If you had $11850 to spend today, what would you buy?",
  "If you had $11900 to spend today, what would you buy?",
  "If you had $11950 to spend today, what would you buy?",
  "If you had $12000 to spend today, what would you buy?",
  "If you had $12050 to spend today, what would you buy?",
  "If you had $12100 to spend today, what would you buy?",
  "If you had $12150 to spend today, what would you buy?",
  "If you had $12200 to spend today, what would you buy?",
  "If you had $12250 to spend today, what would you buy?",
  "If you had $12300 to spend today, what would you buy?",
  "If you had $12350 to spend today, what would you buy?",
  "If you had $12400 to spend today, what would you buy?",
  "If you had $12450 to spend today, what would you buy?",
  "If you had $12500 to spend today, what would you buy?",
  "If you had $12550 to spend today, what would you buy?",
  "If you had $12600 to spend today, what would you buy?",
  "If you had $12650 to spend today, what would you buy?",
  "If you had $12700 to spend today, what would you buy?",
  "If you had $12750 to spend today, what would you buy?",
  "If you had $12800 to spend today, what would you buy?",
  "If you had $12850 to spend today, what would you buy?",
  "If you had $12900 to spend today, what would you buy?",
  "If you had $12950 to spend today, what would you buy?",
  "If you had $13000 to spend today, what would you buy?",
  "If you had $13050 to spend today, what would you buy?",
  "If you had $13100 to spend today, what would you buy?",
  "If you had $13150 to spend today, what would you buy?",
  "If you had $13200 to spend today, what would you buy?",
  "If you had $13250 to spend today, what would you buy?",
  "If you had $13300 to spend today, what would you buy?",
  "If you had $13350 to spend today, what would you buy?",
  "If you had $13400 to spend today, what would you buy?",
  "If you had $13450 to spend today, what would you buy?",
  "If you had $13500 to spend today, what would you buy?",
  "If you had $13550 to spend today, what would you buy?",
  "If you had $13600 to spend today, what would you buy?",
  "If you had $13650 to spend today, what would you buy?",
  "If you had $13700 to spend today, what would you buy?",
  "If you had $13750 to spend today, what would you buy?",
  "If you had $13800 to spend today, what would you buy?",
  "If you had $13850 to spend today, what would you buy?",
  "If you had $13900 to spend today, what would you buy?",
  "If you had $13950 to spend today, what would you buy?",
  "If you had $14000 to spend today, what would you buy?",
  "If you had $14050 to spend today, what would you buy?",
  "If you had $14100 to spend today, what would you buy?",
  "If you had $14150 to spend today, what would you buy?",
  "If you had $14200 to spend today, what would you buy?",
  "If you had $14250 to spend today, what would you buy?",
  "If you had $14300 to spend today, what would you buy?",
  "If you had $14350 to spend today, what would you buy?",
  "If you had $14400 to spend today, what would you buy?",
  "If you had $14450 to spend today, what would you buy?",
  "If you had $14500 to spend today, what would you buy?",
  "If you had $14550 to spend today, what would you buy?",
  "If you had $14600 to spend today, what would you buy?",
  "If you had $14650 to spend today, what would you buy?",
  "If you had $14700 to spend today, what would you buy?",
  "If you had $14750 to spend today, what would you buy?",
  "If you had $14800 to spend today, what would you buy?",
  "If you had $14850 to spend today, what would you buy?",
  "If you had $14900 to spend today, what would you buy?",
  "If you had $14950 to spend today, what would you buy?",
  "If you had $15000 to spend today, what would you buy?"
],
    dares: [
  "Do 10 jumping jacks.",
  "Sing a song for 10 seconds loudly.",
  "Talk with a funny accent for the next 3 rounds.",
  "Do a silly dance for 15 seconds.",
  "Speak in rhyme for the next 5 minutes.",
  "Try to lick your elbow.",
  "Hold your breath for 10 seconds.",
  "Spin around 10 times and try to walk straight.",
  "Act like a dog for 30 seconds.",
  "Act like a cat for 30 seconds.",
  "Act like a elephant for 30 seconds.",
  "Act like a frog for 30 seconds.",
  "Act like a snake for 30 seconds.",
  "Act like a bear for 30 seconds.",
  "Act like a lion for 30 seconds.",
  "Act like a penguin for 30 seconds.",
  "Act like a monkey for 30 seconds.",
  "Act like a rabbit for 30 seconds.",
  "Act like a fish for 30 seconds.",
  "Do 5 pushups while counting loudly.",
  "Do 6 pushups while counting loudly.",
  "Do 7 pushups while counting loudly.",
  "Do 8 pushups while counting loudly.",
  "Do 9 pushups while counting loudly.",
  "Do 10 pushups while counting loudly.",
  "Do 11 pushups while counting loudly.",
  "Do 12 pushups while counting loudly.",
  "Do 13 pushups while counting loudly.",
  "Do 14 pushups while counting loudly."
]
  },
  {
    id: "spicy",
    label: "🌶️ Spicy",
    emoji: "🌶️",
    isSpicy: true,
    truths: [
      "Who in this room do you think is the best looking?",
      "What is your biggest turn-on?",
      "Have you ever sent a risky text to the wrong person? If so, what did it say?",
      "What's your wildest, most adventurous fantasy?",
      "Tell us a juicy secret about your most recent romantic date.",
      "What is the most scandalous rumor you've ever heard about yourself or someone in this room?",
      "Have you ever lied about your age, relationship status, or job to impress a crush?",
      "Who was your most memorable first kiss, and where did it happen?",
      "What is your biggest regret about a past relationship?",
      "Have you ever had a crush on a friend's sibling or partner?",
      "What is a secret about yourself that you've never shared with anyone in this room?",
      "What is the first thing you look for in a potential partner?"
    ],
    dares: [
      "Kiss the cheek of the person to your left.",
      "Send a flirty text to the 5th contact on your phone list.",
      "Let another player sit on your lap for the next round of this game.",
      "Show the group the last three photos in your camera roll.",
      "Maintain intense eye contact with the person across from you for 30 seconds without laughing.",
      "Give a warm, dramatic 10-second hug to the person of your choice.",
      "Whisper a secret about yourself in the ear of the player on your right.",
      "Do a slow, dramatic model walk across the room.",
      "Serenade the person across from you with a love song for 30 seconds.",
      "Let the player to your right send a text of their choice to any contact in your phone.",
      "Let the group style your hair in any way they want, and keep it that way for the rest of the game.",
      "Speak in a seductive whisper for the next two rounds of the game."
    ]
  },
  {
    id: "bollywood",
    label: "🎬 Bollywood",
    emoji: "🎬",
    truths: [
  "Which Bollywood actor is your ultimate crush?",
  "Which Bollywood movie makes you cry every time?",
  "If you had to watch a Bollywood movie 2 times back to back without sleeping, which one would it be?",
  "If you had to watch a Bollywood movie 3 times back to back without sleeping, which one would it be?",
  "If you had to watch a Bollywood movie 4 times back to back without sleeping, which one would it be?",
  "If you had to watch a Bollywood movie 5 times back to back without sleeping, which one would it be?",
  "If you had to watch a Bollywood movie 6 times back to back without sleeping, which one would it be?",
  "If you had to watch a Bollywood movie 7 times back to back without sleeping, which one would it be?",
  "If you had to watch a Bollywood movie 8 times back to back without sleeping, which one would it be?",
  "If you had to watch a Bollywood movie 9 times back to back without sleeping, which one would it be?",
  "If you had to watch a Bollywood movie 10 times back to back without sleeping, which one would it be?",
  "If you had to watch a Bollywood movie 11 times back to back without sleeping, which one would it be?"
],
    dares: [
  "Do the hook step of 'Chaiyya Chaiyya'.",
  "Dance like Hrithik Roshan for 15 seconds.",
  "Re-enact an exaggerated death scene from a classic Hindi movie from the 1970s.",
  "Re-enact an exaggerated death scene from a classic Hindi movie from the 1971s.",
  "Re-enact an exaggerated death scene from a classic Hindi movie from the 1972s.",
  "Re-enact an exaggerated death scene from a classic Hindi movie from the 1973s.",
  "Re-enact an exaggerated death scene from a classic Hindi movie from the 1974s.",
  "Re-enact an exaggerated death scene from a classic Hindi movie from the 1975s.",
  "Re-enact an exaggerated death scene from a classic Hindi movie from the 1976s.",
  "Re-enact an exaggerated death scene from a classic Hindi movie from the 1977s.",
  "Re-enact an exaggerated death scene from a classic Hindi movie from the 1978s.",
  "Re-enact an exaggerated death scene from a classic Hindi movie from the 1979s.",
  "Re-enact an exaggerated death scene from a classic Hindi movie from the 1980s.",
  "Re-enact an exaggerated death scene from a classic Hindi movie from the 1981s.",
  "Re-enact an exaggerated death scene from a classic Hindi movie from the 1982s.",
  "Re-enact an exaggerated death scene from a classic Hindi movie from the 1983s.",
  "Re-enact an exaggerated death scene from a classic Hindi movie from the 1984s.",
  "Re-enact an exaggerated death scene from a classic Hindi movie from the 1985s.",
  "Re-enact an exaggerated death scene from a classic Hindi movie from the 1986s.",
  "Re-enact an exaggerated death scene from a classic Hindi movie from the 1987s.",
  "Re-enact an exaggerated death scene from a classic Hindi movie from the 1988s.",
  "Re-enact an exaggerated death scene from a classic Hindi movie from the 1989s.",
  "Re-enact an exaggerated death scene from a classic Hindi movie from the 1990s.",
  "Re-enact an exaggerated death scene from a classic Hindi movie from the 1991s.",
  "Re-enact an exaggerated death scene from a classic Hindi movie from the 1992s.",
  "Re-enact an exaggerated death scene from a classic Hindi movie from the 1993s.",
  "Re-enact an exaggerated death scene from a classic Hindi movie from the 1994s."
]
  },
  {
    id: "cricket",
    label: "🏏 Cricket",
    emoji: "🏏",
    truths: [
  "Who is your favorite cricketer and why?",
  "Which IPL team do you secretly support?",
  "If you were the captain of India in the 2000 World Cup, what would you do differently?",
  "If you were the captain of India in the 2001 World Cup, what would you do differently?",
  "If you were the captain of India in the 2002 World Cup, what would you do differently?",
  "If you were the captain of India in the 2003 World Cup, what would you do differently?",
  "If you were the captain of India in the 2004 World Cup, what would you do differently?",
  "If you were the captain of India in the 2005 World Cup, what would you do differently?",
  "If you were the captain of India in the 2006 World Cup, what would you do differently?",
  "If you were the captain of India in the 2007 World Cup, what would you do differently?",
  "If you were the captain of India in the 2008 World Cup, what would you do differently?",
  "If you were the captain of India in the 2009 World Cup, what would you do differently?",
  "If you were the captain of India in the 2010 World Cup, what would you do differently?",
  "If you were the captain of India in the 2011 World Cup, what would you do differently?",
  "If you were the captain of India in the 2012 World Cup, what would you do differently?",
  "If you were the captain of India in the 2013 World Cup, what would you do differently?",
  "If you were the captain of India in the 2014 World Cup, what would you do differently?",
  "If you were the captain of India in the 2015 World Cup, what would you do differently?",
  "If you were the captain of India in the 2016 World Cup, what would you do differently?",
  "If you were the captain of India in the 2017 World Cup, what would you do differently?",
  "If you were the captain of India in the 2018 World Cup, what would you do differently?",
  "If you were the captain of India in the 2019 World Cup, what would you do differently?",
  "If you were the captain of India in the 2020 World Cup, what would you do differently?",
  "If you were the captain of India in the 2021 World Cup, what would you do differently?",
  "If you were the captain of India in the 2022 World Cup, what would you do differently?",
  "If you were the captain of India in the 2023 World Cup, what would you do differently?",
  "If you were the captain of India in the 2024 World Cup, what would you do differently?"
],
    dares: [
  "Imitate MS Dhoni's helicopter shot.",
  "Do Jasprit Bumrah's bowling action.",
  "Pretend to bowl an intense final over, running up to the crease 2 times.",
  "Pretend to bowl an intense final over, running up to the crease 3 times.",
  "Pretend to bowl an intense final over, running up to the crease 4 times."
]
  }
];
